#!/usr/bin/env bash
#Install nginx web server with ssh bash command
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo nginx -t
service nginx start
