#!/usr/bin/env bash
#Double my servers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 35.153.19.188:80 check\n\tserver server2 18.210.14.125:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
