#!/usr/bin/env bash
# Install HAProxy on server
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
#config HAProxy on server lb-01 server

#installation
sudo apt-get -y update
sudo apt-get -y install haproxy

#edit config
server_config=\
"
frontend opoku-wiafe_frontend
	bind *:80
	mode http
	default_backend opoku-wiafe_backend
backend opoku-wiafe_backend
	balance roundrobin
	server 317167-web-01 35.153.19.188:80 check
	server 317167-web-02 3.86.7.195:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable and start happroxy service
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
