#!/usr/bin/env bash
# run the same command to nginx but this time shorter
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
